justkey007/tsc-alias

- tsconfig.json
Execute `yarn tsc-alias` on github actions (ubuntu-latest) will get errors: "/usr/bin/env: ‘node\r’: No such file or directory".
According to [https://github.com/yarnpkg/yarn/issues/8106](https://github.com/yarnpkg/yarn/issues/8106), a possible reason is that the current tsc-alias release use `CRLF` as line endings.
So change it to `LF` by adding `newLine` property in tsconfig.
> Set eol to 'LF' in tsconfig

- src/index.ts
Fixes an issue that causes path aliases for `./` to get incorrectly rewritten to `.//*` instead of `./*`.
Given the following `tsconfig.json`:
```json
"baseUrl": "./src",
"paths": {
"my-app": ["./"],
"my-app/*": ["./*"]
}
```
The current code will rewrite `my-app/Foo` to `.//Foo` instead of `./Foo`.
This PR fixes the issue, rewriting the path to  `./Foo`.
> Support empty relative alias paths

- projects/project5/package.json
- projects/project5/src/custom_modules/calculator.ts
- projects/project5/src/custom_modules/index.ts
- projects/project5/src/index.ts
- projects/project5/src/lib/commons/index.ts
- projects/project5/src/scope/index.ts
- projects/project5/tsconfig.json
- src/index.ts
- tests/test.spec.ts
resolve #18 
Regarding `const isAlias = requiredModule.split('/').indexOf(alias.prefix) === 0;` in the change, split(/) does not do the job when it comes to the scoped package but it looks to me that `const isAlias = requiredModule.startsWith(alias.prefix);` is equivalent to it while it fixes the issue so I believe this one-line-change is backward compatible. :)
> add support for scoped package alias

- README.md
It seems watch script example is wrong.
Currently using "&&" So "tsc-alias -w" is not parallel running.
I tested and check completely works this fix on my own project.
> Fix wrong watch script example in README.md

- README.md
- src/bin/index.ts
- src/index.ts
Silent option reduces terminal output.
Tested with/without watch enabled.
Added command line option -s --silent
Updated README
closes #28
> Added silent option

- README.md
- projects/project10/package.json
- projects/project10/src/api/invoice/invoice.service.ts
- projects/project10/src/main.ts
- projects/project10/src/utils/index.ts
- projects/project10/tsconfig.json
- projects/project11/package-lock.json
- projects/project11/package.json
- projects/project11/src/custom_modules/calculator.ts
- projects/project11/src/custom_modules/index.ts
- projects/project11/src/index.ts
- projects/project11/tsconfig.json
- projects/project9/package-lock.json
- projects/project9/package.json
- projects/project9/src/index.ts
- projects/project9/tsconfig.json
- src/bin/index.ts
- src/index.ts
- src/utils/ImportPathResolver.ts
- src/utils/index.ts
- tests/test.spec.ts
Typescript configs allow for both path aliases and node-style module resolution, while not fully supporting either on compile due to not modifying import paths.
`tsc-alias` handles the path aliases part of this problem, but not the overlapping module-resolution problem.
When using ECMAScript modules (ESM) in Node, being able to write in Typescript without full resolution is nice but the compiled JavaScript cannot run because ESM requires full paths.
The new feature attempts to find all import paths and then attempts to resolve them to an existing JavaScript file. If found, it replaces the original with the fully-resolved path.
While this could be done as a standalone tool, being able to use a single tool to resolve path issues in tsc-compiled code would be useful.
Additional changes:
- …
> Add option to fully resolve paths, making compiled code ECMAScript Module-ready

- src/index.ts
- src/utils/output.ts
Fixes #32
Additionally adds minor refactor of entrypoint to convert validator code into single-line assertions.
(Note that I originally wanted to have the assertion be part of the `Output` class, but Typescript gets weird about class methods used as assertion functions.)
> Ensures the process exits with non-zero status even if logging is turned off.

- src/index.ts
- src/utils/ImportPathResolver.ts
I originally added these because they're *technically* allowed, but probably don't work for ESM-style imports and Typescript doesn't like them. Including it probably hurts more than it helps.
I also coupled the search patterns used in various spots so that they're centralized.
Finally, I added an error log for the Issue #34 just in case this doesn't fix it, since that will help triangulate the problem.
> Remove backticks from allowed quote characters for import strings

- src/utils/ImportPathResolver.ts
- tests/test.spec.ts
Closes #36 (with the easy fix)
> Make path-matching regexes more strict to reduce spurious matches

- src/index.ts
As stated in #39, the current implementation doesn't support a tsconfig like this:
```json
{
"compilerOptions": {
"baseUrl": ".",
"paths": {
"#*": [
"src/*"
]
},
}
}
```
This PR will fix the problem and close #39.
> fix: ensure a slash after the prefix

- src/index.ts
Following #43, here is a small change to make path replacement more consistent with typescript's behaviour
Here I consider 3 common path configs:
1. `"path": ["other"]`
2. `"path*": ["other/*"]`
3. `"path/*": ["other/*"]`
This PR will make the following mappings will happen correctly.
`require("path")` -> `require("other")`
`require("pathother")` -> `require("pathother")` // NO CHANGE
`require("pathother/another")` -> `require("pathother/another")` // NO CHANGE
`require("path/other")` -> `require("other/other")`
`require("path/other/another")` -> `require("other/other/another")`
`require("path")` -> `require("path")` // NO CHANGE
`require("pathother")` -> `require("other/other")`
`require("pathother/another")` -> `require("other/other/another")`
`require("path/other")` -> …
> Make path replacement more consistent with typescript's behaviour

- src/index.ts
Closes #49
- Added default baseUrl path. When no baseUrl is specified, then the program will default to project directory.
> Added default baseUrl path

- projects/project16/package.json
- projects/project16/src/file.ts
- projects/project16/src/index.ts
- projects/project16/src/test/testy.ts
- projects/project16/tsconfig.json
- src/helpers/index.ts
- src/index.ts
- src/utils/output.ts
This pull request should fix #63 
- Added support for baseUrl without paths.
- Added test project for feature.
In the performance test is shown that the new feature doesn't add too much overhead.
All results are an average of 5 test runs.
Test specs:
- Ryzen 2700X CPU
- 32GB Ram
- 500GB Samsung 970 Evo SSD (With only the benchmark)
- Node 17.1.0
Result is time in ms.
| AliasCount > | 10   | 20   | 30   | 40   | 50   |  60  | 70   |  80  |  90  | 100   |
|---------|----|----|----|----|----|----|----|----|----|----|
|    10 Files  | 13 | 11 | 11 | 10 | 10 | 12 | 13 | 12 | 14 | 16 |
|    20 Files  | 14 | 16 | 15 | 16 | 17 | 19 | 20 | 20 | 21 | 22 |
|    30 Files  | 18 | 19 | 22 | 22 | 25 | 26 | 27 | 29 | 31 | 32 |
|    40 Files  | 24 | 25 | 26 | 29 | 29 | 31 | 33 | 35 | 37 | 39 |
|    50 …
> Added support for baseUrl without paths

- README.md
- projects/project18/package.json
- projects/project18/src/index.ts
- projects/project18/src/utils/authorization/index.ts
- projects/project18/src/utils/get-spec.ts
- projects/project18/src/utils/index.ts
- projects/project18/src/utils/regex.ts
- projects/project18/src/utils/test-helpers/index.ts
- projects/project18/src/utils/validation.ts
- projects/project18/tsconfig.json
- src/bin/index.ts
- src/helpers/config.ts
- src/index.ts
- src/interfaces.ts
- src/utils/output.ts
- tests/test.spec.ts
Adds the following:
- Add support for configuring `resolveFullPaths` and `verbose` via `tsconfig.json`
- Use `console.error` for printing errors to the terminal
- Add example `tsconfig.json` configuration to README.md
- Add `project18` test for `tsconfig.json` `resolveFullPaths` option
- Add `--verbose` argument defaulting to `false`.
- Deprecate `--silent` argument
- Remove `tsc-alias starting` message from output init
- Prefix output messages with `tsc-alias` to indicate what generated the message
- Remove condition for error output so errors don't cause a silent failure
- Add `output.setVerbose` method to enable controlling verbose setting after the output class is instantiated
This turned in to a slightly larger pull than I expected. I initially set out to add the ability to configure …
> Add support for configuring `resolveFullPaths` and `verbose` via `tsconfig.json`, deprecate `--silent` option

- .gitignore
- README.md
- projects/project19/package.json
- projects/project19/src/index.ts
- projects/project19/src/utils/authorization/index.ts
- projects/project19/src/utils/get-spec.ts
- projects/project19/src/utils/index.ts
- projects/project19/src/utils/regex.ts
- projects/project19/src/utils/test-helpers/index.ts
- projects/project19/src/utils/validation.ts
- projects/project19/tsconfig.json
- src/helpers/config-preparer.ts
- src/helpers/replacers.ts
- src/index.ts
- tests/test.spec.ts
- adding `prepareSingleFileReplaceTscAliasPaths(options?)`, which will return a promise of the singleFileReplacer function, with the config already prepared.
- `SingleFileReplacer` is a function that will receive `{fileContents: string, filePath: string}` and return the treated contents
fix #84
> feat: Support for single file sync processing

- src/interfaces.ts
Small syntax bug in IOutput interface. Typescript gives error TS1131 because set is unknown.
> fix: syntax bug

- projects/project16/package.json
- projects/project16/tsconfig.json
- src/index.ts
This pr fixes #112
When outDir has a trailing slash like: `./dist/` the globPattern would become `./dist//**`, which leads to no files being found.
> Fixed trailing slash

- README.md
fixes #117 
```bash
tsc -w & tsc-alias -w
```
Doesn't seem to work. See #117 
Updated script to:
```bash
concurrently \"tsc -w\" \"tsc-alias -w\"
```
Src: https://github.com/justkey007/tsc-alias/issues/117#issuecomment-1123623945
> Fixed readme build scripts

- src/replacers/default.replacer.ts
When trying to use module resolution set to nodenext/node12 I am forced to add the compiled extension to all of my imports. This is then reflected in my index.d.ts file as it includes the .js extension. I am bundling all the files into one dist file, so the compiled js file doesn't exist which causes the alias to not be replaced. What does exist is the .d.ts file so removing the .js extension makes the path become valid due to it matching the .d.ts file.
> fix(default-replacer): Remove js extension when checking if path is valid

- src/bin/index.ts
- src/helpers/config.ts
- src/helpers/replacers.ts
- src/index.ts
- src/interfaces.ts
- src/replacers/base-url.replacer.ts
- src/replacers/default.replacer.ts
- src/utils/output.ts
Debug mode, enabled with `--debug`, logs debug information to the console. This is useful for debugging and troubleshooting. When debug is disabled the debug function is empty to prevent constant checking of debug state.
Troubleshooting tsc-alias is difficult when config doesn't load, or files aren't found.
Adding a debug mode to debug the configuration. for example, to see what config is loaded, which files are found or why an alias isn't being replaced.
An empty default function is used to prevent the program from checking if it should log the debug data. Making the function optional would place this check at every debug point in the code. By making a default empty function and only replacing that in the constructor ensures that the check is only done once.
All results are an average of …
> Added debug mode

- projects/project22/package.json
- projects/project22/src/custom_modules/find-json.ts
- projects/project22/src/data.json
- projects/project22/src/index.ts
- projects/project22/tsconfig.json
- src/replacers/default.replacer.ts
- tests/test.spec.ts
This PR solves the following problem.
```javascript
console.log(`(?:\.(js|json)$)`); // results (?:.(js|json)$).
```
- This expression would match "{any character}js" or "{any character}json" when it is expected to match ".js" or ".json" .
- If the file name ends with "-json.js", the import will fail as in the attached test project22.
> fix(default-replacer): `(?:\.(js|json)$)` should be replaced by `(?:\\.(js|json)$)`

- projects/project9/src/index.ts
- projects/project9/tsconfig.json
- src/helpers/path.ts
- tests/test.spec.ts
> fix: reference in node_modules folder

- README.md
- projects/project9/package.json
- projects/project9/src/index.ts
- projects/project9/tsconfig.json
- src/utils/import-path-resolver.ts
This pr should fix #137
- Added check if import path is equal to `.`
- Updated readme with debug option
Project9 failed because of a change in the dependencies of the dependency that was used to check if resolution to a node_module works. Changed the dependency used by the test to a pinned version of a dependency with no dependencies.
> Bug index full path resolution

- README.md
- src/bin/index.ts
- src/helpers/config.ts
- src/index.ts
- src/interfaces.ts
- src/utils/path-cache.ts
Added the options to overwrite the file scanning glob and to overwrite the file resolution glob.
@justkey007 Does this feature fall within the project scope?
Implements feature request #149
> File extensions settings

- src/utils/import-path-resolver.ts
support import path with comment，such as:
`await import(/* webpackChunkName: "alias-chunk" */ "@root/test/alias")`
> fix: suport import function with  webpackChunkName comment

- src/utils/trie.ts
I met a problem when use this tool. Here is my `tsconfig.json`:
```json
{
"compilerOptions": {
"outDir": "es",
"baseUrl": ".",
"paths": {
"my-list/utils/*": ["/some-absolute-path/example/src/utils/*"]
}
},
"include": ["src/**/*.ts", "src/**/*.tsx"]
}
```
**This `tsconfig.json` is out of my package folder, it is in the `node_module/cache` folder.** When I use `tsc-alias` to transform the alias configured by `tsconfig.json`, I got this exception:
[This line](https://github.com/justkey007/tsc-alias/blob/master/src/helpers/path.ts#L84) shows that you judge if it's an alias references a file outside the `baseUrl` via `aliasPath.path.includes('..')`.However [this line](https://github.com/justkey007/tsc-alias/blob/master/src/utils/trie.ts#L86) shows that `aliasPath.path` is a path relative to …
> fix: replacer got an invalid path if tsconfig.json is out of package dir

- src/helpers/replacers.ts
- src/index.ts
- src/interfaces.ts
- src/utils/import-path-resolver.ts
Hi, this library is all I need. Using it with esbuild is great combo. But I miss something
First, when the target files is minified version (esbuild minify=true), then It will not replace anything. Because minified version is look like this
```js
import"something";
import{X}from"something";
```
As you can see, there is no space after import and from statement. I add regex to cover this situation, please correct me is the regex can be simplified.
Second, when using `resolveFullPath` option, this library only search for `.js` extension. My project is full esm, it's using `.mjs`. So I create additional option to cover this, so It can be adjusted to search `.mjs` or `.cjs`. By default it will search `.js`. I don't know if it's the best way.
> feat: custom extension for resolveFullPath and add regex for minified js

- README.md
As per the options of the `tsc-alias` command, the correct parameter would be `project` instead of `configFile`, since the latter is only used internally. https://github.com/justkey007/tsc-alias/blob/de8a5bc03635f1823742b6b4c7614930f0ecfcf0/src/bin/index.ts#L10
> Docs: Update the "project" flag since "configFile" does not exist as a parameter

- src/bin/index.ts
Add resolveFullExtension option to the cli with guards around the accepted values
> feat: add resolveFullExtension to cli

- src/helpers/config.ts
A command like `tsc-alias -p tsconfig.json --inputglob js --outputcheck js` currently fatals with
```
fileExtensions.inputGlob = options.fileExtensions.inputGlob;
^
TypeError: Cannot set properties of undefined (setting 'inputGlob')
```
because the removed lines leave `fileExtensions` unset when used with a config that doesn't contain that field. (A workaround is to put a dummy `"tsc-alias": { "fileExtensions": {} }` in tsconfig.json.)
> fix: make `--inputglob` and `--outputcheck` work on their own
