justkey007/tsc-alias

src/index.ts

Reverts justkey007/tsc-alias#7

Revert "Support empty relative alias paths"

---

src/bin/index.ts

The CLI version was old, so it was fixed.

Fix version

---

projects/project13/package.json
projects/project13/src/aaaaaa/index.ts
projects/project13/src/bbbbbb/index.ts
projects/project13/src/cccccc/index.ts
projects/project13/src/controllers/index.ts
projects/project13/src/dddddd/index.ts
projects/project13/src/eeeeee/index.ts
projects/project13/src/ffffff/index.ts
projects/project13/src/gggggg/index.ts
projects/project13/src/hhhhhh/index.ts
projects/project13/src/index.ts
projects/project13/tsconfig.json
src/bin/index.ts
src/index.ts
tests/test.spec.ts

fixes #30 
- Added small performance test.
- Implemented asynchronous File IO.
- Tested globbyStream but compile time doubled (In project13, globbyStream: 36ms, this solution: 17ms, measured from start glob scan to finish replaceCount)

Implemented asynchronous File IO

---

src/index.ts

Change-Id: I0a81bea13743525a2e9d55f991b51f57463a6512

fix: watching file add

---

projects/project15/config/tsconfig.json
projects/project15/package.json
projects/project15/src/aaaaaa/index.ts
projects/project15/src/bbbbbb/index.ts
projects/project15/src/cccccc/index.ts
projects/project15/src/controllers/index.ts
projects/project15/src/dddddd/index.ts
projects/project15/src/eeeeee/index.ts
projects/project15/src/ffffff/index.ts
projects/project15/src/gggggg/index.ts
projects/project15/src/hhhhhh/index.ts
projects/project15/src/index.ts
src/bin/index.ts
tests/test.spec.ts

- Added test project to test with options.
- fixed commander options being undefined.

fix: Commander options undefined

---

projects/project16/tsconfig.json
src/helpers/config.ts
src/helpers/replacers.ts
src/index.ts
src/interfaces.ts
src/replacers/BaseUrl.replacer.ts
src/replacers/default.replacer.ts

Moved replacers to own file.
Added disable functionality.
Added functionality to add or remove replacers via tsconfig

Moved replacers to own file & Added disable functionality

---

README.md
src/helpers/replacers.ts

Added replacer documention.
Small bugfix.
Added tutorial on replacers in [github discussions](https://github.com/justkey007/tsc-alias/discussions/73).

Replacer documentation

---

README.md
src/helpers/path.ts
src/helpers/replacers.ts
src/index.ts
src/interfaces.ts
src/utils/output.ts
src/utils/trie.ts

- Fixed typo in readme
- Added AliasTrieBuilder
- Moved replaceAlias to replacers.ts
- Split up config into project related config and total
- Added aliasTrie to options (so in case of issue #69 the aliasTrie wouldn't be build twice)
All tests are passing.
No measurable performance impact.

Added AliasTrieBuilder, moved replaceAlias to replacers.ts, Fixed typo

---

src/helpers/config.ts
src/helpers/replacers.ts
src/index.ts
src/interfaces.ts

Reverts justkey007/tsc-alias#86

Revert "Added replaceInString & getConfig"

---

projects/project12/src/index.ts
projects/project12/tsconfig.json
src/replacers/default.replacer.ts

This should fix #83's `$` bug.
Added `$` to test.

Fixed regex special characters bug

---

package.json
pnpm-lock.yaml
projects/project16/package.json
projects/project16/replacer.js
src/helpers/config.ts
src/helpers/path.ts
src/helpers/replacers.ts
src/replacers/BaseUrl.replacer.ts
src/replacers/default.replacer.ts
src/utils/import-path-resolver.ts
src/utils/output.ts
tests/test.spec.ts
tsconfig.json

This pr should fix #93.
Fixed bug that made replacers load as esModule.

Fix: replacer esModule bug

---

src/index.ts
src/utils/output.ts

fix: 1.6.2 on windows

---

src/helpers/config.ts
src/index.ts

This issue fixes #100
Tested on: https://github.com/gbenson-ff/tsc-alias-bug

Fix: relative tsconfig paths

---

src/helpers/path.ts
tests/test.spec.ts

- Fixed #107 
- Fixed windows bug in tests
All tests are passing on Windows and Linux.
No real performance impact.

Fix: getProjectDirPathInOutDir windows bug

---

package.json
pnpm-lock.yaml
src/index.ts

I've tried adding `p-limit` but version 4 didn't have commonjs and version 3 had a d.ts error.
Used `plimit-lit` and that worked fine.
Tests passing
This pr should fix #114

Added promise limiter

---

src/replacers/default.replacer.ts

like https://github.com/justkey007/tsc-alias/pull/123 but i want to import a json or any other file.

feat: ignore any extension

---

src/helpers/config.ts

Added symlink check for tsconfig resolving

---

README.md

See #117
Changed watch script to `tsc && (concurrently \"tsc -w\" \"tsc-alias -w\")` because of [this](https://github.com/justkey007/tsc-alias/issues/117#issuecomment-1234674874) issue

Updated watch script docs

---

src/helpers/config.ts

This pr fixes the issue of the cli input overwriting the config input with undefined

Fixed file extension undefined

---

src/bin/index.ts

Added outDir option to cli

---

projects/project23/package.json
projects/project23/src/i18n/index.ts
projects/project23/src/index.ts
projects/project23/tsconfig.json
src/helpers/config.ts
src/helpers/replacers.ts
tests/test.spec.ts

Closes https://github.com/justkey007/tsc-alias/issues/169

Enable baseUrl replacer only when baseUrl option is set in tsconfig.json

---

src/helpers/config.ts

fix `ext.startsWith('.')` error when `extends` option set to an array #172

fix: support tsconfig extends option to be an array

---

src/replacers/default.replacer.ts

feat: resolve aliases with ts extensions (#178)

---

src/helpers/config.ts

https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-configdir-template-variable-for-configuration-files
Was going try adding a test, but ran into difficulties with older packages and current tests failing prior to my change which may be related to my system having pnpm 9 and having to update the lockfile and potentially pulling in new dependencies.

feat: support typescript 5.5  template
